# Generated by Django 5.0.2 on 2024-02-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='job_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
