# Generated by Django 5.0.2 on 2024-02-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_quotation_job_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='job_start',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Within a week', 'Within a week'), ('Within two week', 'Within two week'), ('Within a month', 'Within a month'), ('Within two month', 'Within two month'), ('Flexible Date', 'Flexible Date')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='property_ownership',
            field=models.CharField(choices=[('I own and live at this property ', 'I own and live at this property'), ('I am a Landlord ', 'I am a Landlord'), ('I am a tenent but authorize to change', 'I am a tenent but authorize to change'), ('I am planing to buy', 'I am planing to buy')], max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='stage',
            field=models.CharField(choices=[('I am ready to hire ', 'I am ready to hire '), ('I am palning & budgeting ', 'I am palning & budgeting '), ('I need a qoute for Insurance ', 'I need a qoute for Insurance ')], max_length=200),
        ),
    ]
