# Generated by Django 5.0.2 on 2024-02-09 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('backend', '0003_alter_quotation_job_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
    ]
