# Generated by Django 5.0.2 on 2024-02-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_zip_code_userprofile_postal_code_and_more'),
        ('backend', '0004_quotation_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('order_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_details', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Work in Progress', 'Work in Progress'), ('Assign', 'Assign'), ('Not Assign', 'Not Assign'), ('Completed', 'Completed')], default='Not Assign', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.quotation')),
            ],
        ),
    ]
