# Generated by Django 5.0.2 on 2024-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_image_quotationpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assign', 'Assign'), ('Win', 'Win'), ('Lost', 'Lost'), ('Not Interested', 'Not Interested')], default='Pending', max_length=50),
        ),
    ]
