# Generated by Django 5.0.2 on 2024-02-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quotation',
            field=models.CharField(max_length=100),
        ),
    ]
