# Generated by Django 5.0.2 on 2024-02-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_order_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.quotation'),
        ),
    ]
