# Generated by Django 5.0.2 on 2024-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_order_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
