# Generated by Django 5.0.2 on 2024-02-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_order_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='quotations', to='backend.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_images', to='backend.quotation'),
        ),
    ]
