# Generated by Django 5.0.2 on 2024-02-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_quotation_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='subCategory',
        ),
    ]
