# Generated by Django 5.0.2 on 2024-02-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_quotation_category_and_more'),
        ('frontend', '0010_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.category'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.subcategory'),
        ),
    ]
