# Generated by Django 4.1 on 2024-02-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_quotation_category_quotation_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationpricing',
            old_name='date',
            new_name='assesment_date',
        ),
    ]
