# Generated by Django 4.1 on 2024-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_date_quotationpricing_assesment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
