# Generated by Django 4.1 on 2024-02-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_quotation_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='user',
            new_name='customer',
        ),
    ]
