# Generated by Django 5.0.2 on 2024-02-09 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0004_remove_category_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('userrole', models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('Trade Person', 'Trade Person')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/images')),
                ('photo_id', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/photo_ID')),
                ('is_active', models.BooleanField(default=False)),
                ('expertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.category')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
