# Generated by Django 5.0.2 on 2024-02-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
    ]
