# Generated by Django 5.0.2 on 2024-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_zip_code_userprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userrole',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff'), ('Trade Person', 'Trade Person')], max_length=50),
        ),
    ]
