# Generated by Django 5.0.2 on 2024-02-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='show',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
