# Generated by Django 4.1 on 2024-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
